#!/usr/bin/env node
// Exports the ABIs of the public Accrue contracts from Foundry artifacts into the SDK as
// `as const` TypeScript so viem can infer every function, event and error.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, "..", "out");
const target = resolve(here, "..", "..", "sdk", "src", "abis");

const contracts = [
  "AccrueEscrow",
  "SLAHook",
  "ReputationHook",
  "ComplianceHook",
  "HookRouter",
  "Evaluator",
  "AdvancePool",
  "CreditScorer",
  "CredentialRegistry",
  "MockYieldVault",
  "MockUSDC",
];

mkdirSync(target, { recursive: true });
const index = [];
for (const name of contracts) {
  const file = join(out, `${name}.sol`, `${name}.json`);
  if (!existsSync(file)) {
    console.error(`missing artifact ${file}; run forge build first`);
    process.exit(1);
  }
  const artifact = JSON.parse(readFileSync(file, "utf8"));
  const varName = `${name[0].toLowerCase()}${name.slice(1)}Abi`;
  const body = `// Generated by packages/contracts/scripts/export-abis.mjs — do not edit.\nexport const ${varName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  writeFileSync(join(target, `${name}.ts`), body);
  index.push(`export { ${varName} } from "./${name}.js";`);
}
// Minimal external ABIs the SDK also needs.
const erc20 = [
  { type: "function", name: "approve", stateMutability: "nonpayable", inputs: [{ name: "spender", type: "address" }, { name: "amount", type: "uint256" }], outputs: [{ type: "bool" }] },
  { type: "function", name: "allowance", stateMutability: "view", inputs: [{ name: "owner", type: "address" }, { name: "spender", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ name: "account", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
  { type: "function", name: "symbol", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { type: "function", name: "transfer", stateMutability: "nonpayable", inputs: [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }], outputs: [{ type: "bool" }] },
  { type: "event", name: "Transfer", inputs: [{ name: "from", type: "address", indexed: true }, { name: "to", type: "address", indexed: true }, { name: "value", type: "uint256", indexed: false }] },
];
const erc8004Identity = [
  { type: "function", name: "register", stateMutability: "nonpayable", inputs: [{ name: "agentURI", type: "string" }], outputs: [{ name: "agentId", type: "uint256" }] },
  { type: "function", name: "ownerOf", stateMutability: "view", inputs: [{ name: "agentId", type: "uint256" }], outputs: [{ type: "address" }] },
  { type: "function", name: "tokenURI", stateMutability: "view", inputs: [{ name: "agentId", type: "uint256" }], outputs: [{ type: "string" }] },
  { type: "function", name: "getAgentWallet", stateMutability: "view", inputs: [{ name: "agentId", type: "uint256" }], outputs: [{ type: "address" }] },
  { type: "event", name: "Registered", inputs: [{ name: "agentId", type: "uint256", indexed: true }, { name: "agentURI", type: "string", indexed: false }, { name: "owner", type: "address", indexed: true }] },
];
const erc8004Reputation = [
  { type: "function", name: "getSummary", stateMutability: "view", inputs: [{ name: "agentId", type: "uint256" }, { name: "clientAddresses", type: "address[]" }, { name: "tag1", type: "string" }, { name: "tag2", type: "string" }], outputs: [{ name: "count", type: "uint64" }, { name: "summaryValue", type: "int128" }, { name: "summaryValueDecimals", type: "uint8" }] },
  { type: "function", name: "readAllFeedback", stateMutability: "view", inputs: [{ name: "agentId", type: "uint256" }, { name: "clientAddresses", type: "address[]" }, { name: "tag1", type: "string" }, { name: "tag2", type: "string" }, { name: "includeRevoked", type: "bool" }], outputs: [{ name: "clients", type: "address[]" }, { name: "feedbackIndexes", type: "uint64[]" }, { name: "values", type: "int128[]" }, { name: "valueDecimals", type: "uint8[]" }, { name: "tag1s", type: "string[]" }, { name: "tag2s", type: "string[]" }, { name: "revokedStatuses", type: "bool[]" }] },
  { type: "event", name: "NewFeedback", inputs: [{ name: "agentId", type: "uint256", indexed: true }, { name: "clientAddress", type: "address", indexed: true }, { name: "feedbackIndex", type: "uint64", indexed: false }, { name: "value", type: "int128", indexed: false }, { name: "valueDecimals", type: "uint8", indexed: false }, { name: "indexedTag1", type: "string", indexed: true }, { name: "tag1", type: "string", indexed: false }, { name: "tag2", type: "string", indexed: false }, { name: "endpoint", type: "string", indexed: false }, { name: "feedbackURI", type: "string", indexed: false }, { name: "feedbackHash", type: "bytes32", indexed: false }] },
];
const erc4626 = [
  { type: "function", name: "asset", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "totalAssets", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "previewRedeem", stateMutability: "view", inputs: [{ name: "shares", type: "uint256" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "convertToAssets", stateMutability: "view", inputs: [{ name: "shares", type: "uint256" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ name: "account", type: "address" }], outputs: [{ type: "uint256" }] },
];
for (const [name, abi] of [["erc20", erc20], ["erc8004Identity", erc8004Identity], ["erc8004Reputation", erc8004Reputation], ["erc4626", erc4626]]) {
  writeFileSync(join(target, `${name}.ts`), `// Hand-written minimal ABI.\nexport const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`);
  index.push(`export { ${name}Abi } from "./${name}.js";`);
}
writeFileSync(join(target, "index.ts"), index.join("\n") + "\n");
console.log(`exported ${contracts.length + 4} ABIs to ${target}`);
